### ISSUE TITLE
Need info

### ISSUE THREAD

**Issue by roy-shantanu** [appium/appium-docker-android#104] opened 2019-05-08 16:05 UTC
Why do we mount - "~/.android:/root/.android". I was wondering what's actually happening here, I am a bit unsure of its use. The container seems to perfectly run my tests without it.

**Comment by budtmo** [comment] 2019-05-29 12:59
Hi, 

it is need to avoid authorization windows each time you run the container. 
I will close this issue because it is not a bug, but feel free to reopen it if needed.

**Closed by budtmo** 2019-05-29 12:59 UTC
