### ISSUE TITLE
Grid nodes is not shown in console

### ISSUE THREAD

**Issue by Vault23** [appium/appium-docker-android#106] opened 2019-06-10 07:17 UTC
Hello.
I have done everything according to the instruction and successfully initialize grid and appium server. I can see in the console, that appium found 8 devices and a string telling that appium successfully registered with the grid. But, when i go to the grid console i cant see any device. 
And another question: Should appium automatically create appium instance for each device connected to the machine? In example, like i said above, if i have 8 devices, so after successfull compose, will i have 8 appium server instances for each device connected with the grid? Or i need to modify docker-compose yml file for each device and pass parameters here? Thank you in advance.

**Comment by Vault23** [comment] 2019-06-10 09:01
i ve made some investigations and realized that i was trying to connect to another host as a selenium grid host. So now i can see one appium instance with all my devices listed in capabilities, as far as i know appium does not support parallel working with multiple devices, right? So in this case i will not be able to testing in parallel all my devices? If so, maybe there is a trick for that opportunity?

**Comment by budtmo** [comment] 2019-07-09 12:36
Hi @Vault23 , 

Appium support parallel run by using just one Appium server. The issue that you have is connection issue in my opinion, e.g. Firewall, etc. 

I will close this issue because it is not a bug, please feel free to reopen it if needed.

**Closed by budtmo** 2019-07-09 12:36 UTC

**Comment by budtmo** [comment] 2019-07-09 12:37
@Vault23 you can check [this page](http://appium.io/docs/en/advanced-concepts/parallel-tests/)
