### ISSUE TITLE
docker cp C:\Rajesh\Niki\apk File\app-release.apk container-appium:/opt getting some error

### ISSUE THREAD

**Issue by RajeshThakur1** [appium/appium-docker-android#111] opened 2019-08-31 23:44 UTC
when I am running the given command to copy the apk file Local system to the container 
docker cp C:\Rajesh\Niki\apk File\app-release.apk container-appium:/opt

I am getting this error

"docker cp" requires exactly 2 arguments.
See 'docker cp --help'.

Usage:  docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
        docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH

Copy files/folders between a container and the local filesystem

But I already specified the two-argument 1st one is my Local system path another is my container path.

Kindly Help me..
Thanks in advance

**Comment by budtmo** [comment] 2019-09-11 10:38
Hi, 

probably the name of the container is wrong. but you can also use share volume as alternative.
I will close this ticket because it is not a bug.

**Closed by budtmo** 2019-09-11 10:38 UTC
